-
  environment:
    CoverityProjectToken:
      secure: 1mtSEr5uFQI5rdwItPXrR1y4fV+SUWt55lUSQB5o3x8=
    CoverityNotificationEmail:
      secure: 0SPcT7MZEWl9NsqpKSOoLBCfqx/KVDAte5+xvbRremg=
    global:
      CYG_INSTALLER: setup-x86.exe
      CYG_MIRROR: http://cygwin.mirror.constant.com
      CYG_ROOT: C:\cygwin
      CYG_CACHE: C:\cygwin\var\cache\setup
      CYG_BASH: C:\cygwin\bin\bash
      CYG64_INSTALLER: setup-x86_64.exe
      CYG64_ROOT: C:\cygwin64
      CYG64_BASH: C:\cygwin64\bin\bash
      CYG64_CACHE: C:\cygwin64\var\cache\setup
      MSYS2_LOG_FILE: C:/Users/appveyor/msys2output.log

  os: Visual Studio 2015
  version: 1.0.0-{build}
  configuration:
  - All
  - Coverity
  - FsTest
  platform:
  - x64
  
  cache:
  - '%CYG_CACHE%'
  - '%CYG64_CACHE%'

  init:
    - cmd: 'IF "%PLATFORM%" == "x86" (set MSYS2_PATH=C:\\msys64\\mingw32_shell.bat) ELSE (set MSYS2_PATH=C:\\msys64\\mingw64_shell.bat)'

  install:
    - ps: |
        if ($env:CONFIGURATION -eq "All") {
          Start-FileDownload "https://cygwin.com/setup-x86.exe" -FileName "setup-x86.exe"
          Start-FileDownload "https://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"
        }

    - 'IF "%CONFIGURATION%" == "All" ( %CYG_INSTALLER% --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages cmake,make,gcc-core,gcc-g++,mingw-runtime,mingw-binutils,mingw-gcc-core,mingw-gcc-g++,mingw-pthreads,mingw-w32api > NUL 2>&1 
      && %CYG_BASH% -lc "cygcheck -dc cygwin" ) '
    - 'IF "%CONFIGURATION%" == "All" ( %CYG64_INSTALLER% --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --root "%CYG64_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG64_CACHE%" --packages cmake,make,gcc-core,gcc-g++,mingw-runtime,mingw-binutils,mingw-gcc-core,mingw-gcc-g++,mingw-pthreads,mingw-w32api > NUL 2>&1 
      && %CYG64_BASH% -lc "cygcheck -dc cygwin" ) '
    - 'IF "%CONFIGURATION%" == "All" ( C:\msys64\usr\bin\pacman --sync --refresh --refresh --needed --noconfirm msys2-runtime msys2-runtime-devel bash pacman pacman-mirrors 
      && C:\msys64\usr\bin\pacman --noconfirm --sync pacman-mirrors && C:\msys64\usr\bin\pacman -Syu --noconfirm ) '
      # C:\msys64\usr\bin\pacman -S mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-i686-cmake mingw-w64-x86_64-cmake make --noconfirm
    - ps: |
        if ($env:CONFIGURATION -eq "FsTest") {
          & Bcdedit.exe -set TESTSIGNING ON;
          echo "Before reboot";
          Restart-Computer -Force;
          Start-Sleep -s 10;
        }

  build_script:
  - ps: |
      Write-Host Start building...
      $buildCmd = "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe"

      if ($env:CONFIGURATION -eq "Coverity") {
        
        if ("$env:APPVEYOR_PULL_REQUEST_TITLE" -or !($env:APPVEYOR_REPO_BRANCH -eq 'master')) {
          return;
        }
        
        $buildArgs = @(
        "/m",
        "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
        "/p:Configuration=Win10 Debug",
        "/p:Platform=$env:PLATFORM")
          
        & "cov-build.exe" `
        --dir cov-int `
        --encoding=UTF-8 `
        $buildCmd $buildArgs

        nuget install -ExcludeVersion PublishCoverity
        "Compressing Coverity results..."
        & PublishCoverity\tools\PublishCoverity.exe compress `
        --nologo `
        -i "$env:APPVEYOR_BUILD_FOLDER\cov-int" `
        -o "$env:APPVEYOR_BUILD_FOLDER\coverity.zip" `
        --overwrite
        
         "Uploading Coverity results..."  
        & PublishCoverity\tools\PublishCoverity.exe publish `
        --nologo `
        -t "$env:CoverityProjectToken" `
        -e "$env:CoverityNotificationEmail" `
        -r "dokan-dev/dokany" `
        -z "coverity.zip" `
        -d "Appveyor build." `
        --codeVersion "$env:APPVEYOR_BUILD_VERSION"
      
      } elseif ($env:CONFIGURATION -eq "All") {

        $env:Path = $env:Path + ";C:\Program Files (x86)\WiX Toolset v3.10;C:\Program Files (x86)\Windows Kits\8.1\bin\x64\"
        
        & .\build.bat
        
        Write-Host Install cert and sign...
        .\cert\dokan-import.ps1
        .\cert\dokan-sign.ps1
        $env:CERTISSUER="DokanCA"
        $env:ADDITIONALCERT="$pwd\cert\DokanCA.cer"
        $env:SIGNTOOL="C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe"
        Write-Host Binaries signed !	
        
        cd dokan_wix
        (gc version.xml) -replace 'no', 'yes' | sc version.xml
        
        $Platform = "Mixed Platforms"
        $buildArgs = @(
        "Dokan_WiX.sln",
        "/m",
        "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
        "/p:Configuration=Release",
        "/p:Platform=${Platform}")
        
        & $buildCmd $buildArgs
        
        Write-Host Upload Artifcat...
        Push-AppveyorArtifact C:\projects\dokany\dokan_wix\Bootstrapper\bin\Release\DokanSetup.exe -FileName "DokanSetup.exe"
        Write-Host Artifcat uploaded!
        
      } elseif ($env:CONFIGURATION -eq "FsTest") {
        
        $buildArgs = @(
        "/m",
        "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
        "/p:Configuration=Win10 Debug",
        "/p:Platform=$env:PLATFORM")
        
        & $buildCmd $buildArgs

        $certMgr = "C:\Program Files (x86)\Windows Kits\10\bin\x64\certmgr.exe"
        & $certMgr /add x64\Win10Debug\dokan1.cer /s /r localMachine root
        & $certMgr /add x64\Win10Debug\dokan1.cer /s /r localMachine trustedpublisher
        
        cp .\x64\Win10Debug\dokan1.sys C:\Windows\System32\drivers\
        & .\x64\Debug\dokanctl.exe /i d
        & .\x64\Debug\dokanctl.exe /i n
        $app = Start-Process -passthru .\x64\Debug\mirror.exe -ArgumentList "/r C:\TMP /l m"
        Start-Sleep -s 5
        
        git clone https://github.com/Liryna/winfstest.git
        $buildArgs = @(
        ".\winfstest\winfstest.sln",
        "/m",
        "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
        "/p:Configuration=Debug",
        "/p:Platform=$env:PLATFORM")
        
        New-Item C:\TMP -type directory
        & $buildCmd $buildArgs
        & .\winfstest\TestSuite\run-winfstest.bat . M:\

        Start-Sleep -s 5
        Stop-Process $app.Id
      }
      Write-Host Build Finished !

